server:
  port: 8082
  context: "/accounts-management-service"
jwt:
  signingkey: "secret-key"
  expiration: 600000
database:
  host: localhost
  port: 5432
  dbname: accountsmanagement
  username: postgres
  password: password
  sslmode: disable